# Generated by Django 2.1.2 on 2018-11-17 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20181117_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfomodel',
            name='user',
            field=models.ForeignKey(default=223, on_delete=django.db.models.deletion.CASCADE, related_name='userinfo', to='index.UserModel', verbose_name='用户'),
            preserve_default=False,
        ),
    ]
