# Generated by Django 2.1.2 on 2018-11-15 02:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='标题')),
                ('jianjie', models.TextField(verbose_name='简介')),
                ('content', models.TextField(verbose_name='内容')),
                ('htmlcontent', models.TextField(verbose_name='带有样式')),
                ('popular', models.IntegerField(default=0, verbose_name='人气指数')),
                ('recommend', models.BooleanField(default=False, verbose_name='是否推荐')),
                ('tupian', models.FileField(upload_to='static/images', verbose_name='封面图片')),
                ('author', models.CharField(max_length=30, verbose_name='作者')),
                ('create_time', models.CharField(max_length=100, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
                'db_table': 'article',
            },
        ),
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=20, verbose_name='文章分类名称')),
                ('number', models.IntegerField(default=0, verbose_name='排序字段')),
            ],
            options={
                'verbose_name': '文章分类',
                'verbose_name_plural': '文章分类',
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='CommentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=140, verbose_name='评论内容')),
                ('create_time', models.DateTimeField(default=datetime.datetime(2018, 11, 15, 10, 9, 48, 523642), verbose_name='创建时间')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.ArticleModel', verbose_name='文章')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.UserModel', verbose_name='评论的用户')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
                'db_table': 'comment',
            },
        ),
        migrations.CreateModel(
            name='HuifuModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=140, verbose_name='回复内容')),
                ('create_time', models.DateTimeField(default=datetime.datetime(2018, 11, 15, 10, 9, 48, 524641), verbose_name='回复时间')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.CommentModel', verbose_name='回复的评论')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.UserModel', verbose_name='回复人')),
            ],
            options={
                'verbose_name': '回复',
                'verbose_name_plural': '回复',
                'db_table': 'huifu',
            },
        ),
        migrations.CreateModel(
            name='ZanModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(max_length=50, verbose_name='点赞人')),
                ('is_zan', models.IntegerField(default=0)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.ArticleModel', verbose_name='点赞文章')),
            ],
            options={
                'verbose_name': '点赞',
                'verbose_name_plural': '点赞',
                'db_table': 'zan',
            },
        ),
        migrations.AddField(
            model_name='articlemodel',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.CategoryModel', verbose_name='文章分类'),
        ),
    ]
