# Generated by Django 2.1.2 on 2018-11-17 09:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20181117_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmodel',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 17, 17, 53, 27, 679371), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='huifumodel',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 17, 17, 53, 27, 680369), verbose_name='回复时间'),
        ),
    ]
